In [1]:
import numpy as np

In [2]:
def initialize_population( num_individuals, num_variables ):
    """
    Khởi tạo quần thể gồm num_individuals cá thể. Mỗi cá thể có num_parameters biến.
    
    Arguments:
    num_individuals -- Số lượng cá thể
    num_variables -- Số lượng biến
    
    Returns:
    pop -- Ma trận (num_individuals, num_variables ) chứa quần thể mới được khởi tạo ngẫu nhiên.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ###
    pop = np.random.randint(2, size=(num_individuals, num_variables))
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return pop

In [3]:
np.random.seed(19521432)
pop = initialize_population(8,4)
print(pop)

[[1 0 0 1]
 [1 1 1 0]
 [1 1 1 1]
 [0 1 0 1]
 [1 1 1 0]
 [1 1 0 1]
 [0 1 1 0]
 [0 0 1 1]]


In [4]:
def onemax( ind ):
    """
    Hàm đánh giá OneMax: Đếm số bit 1 trong chuỗi nhị phân (cá thể ind).
    
    Arguments:
    ind -- Cá thể cần được đánh giá.

    Returns:
    value -- Giá trị của cá thể ind.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ###     
    value = np.sum(ind)
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return value

In [5]:
onemax(pop[5,:])

3

In [6]:
def tournament_selection(pool, pool_fitness, tournament_size=4):
  num_individuals = len(pool)

  result = []

  for _ in range(2):
    indicies = np.arange(num_individuals)
    np.random.shuffle(indicies)
    
    for i in range(0, num_individuals, tournament_size):
      current_idx = list(indicies[i:i+tournament_size])

      fitness_points = []
      for idx in current_idx:
        fitness_points.append(pool_fitness[idx])
      
      best_fit_idx = current_idx[fitness_points.index(max(fitness_points))]

      result.append(best_fit_idx)
  
  return result

In [7]:
def crossover( pop ):
    """
    Hàm biến đổi tạo ra các cá thể con.
    
    Arguments:
    pop -- Quàn thể hiện tại.

    Returns:
    offspring -- Quần thể chứa các cá thể con được sinh ra.
    """  
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    indices = np.arange(num_individuals)
    # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể
    np.random.shuffle(indices)
    offspring = []
    
    for i in range(0, num_individuals, 2):
        idx1 = indices[i]
        idx2 = indices[i+1]
        offspring1 = list(pop[idx1])
        offspring2 = list(pop[idx2])
        
        # Cài đặt phép lai đồng nhất uniform crossover. 
        # Không cần cài đặt đột biến mutation.
        for idx in range(0, num_parameters):
            r = np.random.rand()
            if r < 0.5:
                temp = offspring2[idx] 
                offspring2[idx] = offspring1[idx]
                offspring1[idx] = temp

        offspring.append(offspring1)
        offspring.append(offspring2)


    ### DỪNG CODE TẠI ĐÂY ###
    
    offspring = np.array(offspring)
    return offspring

In [8]:
# No use in POPOP implementation
def mutation(pop, mutation_prob):
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    for i in range(0, num_individuals):
        for j in range(0, num_parameters):
            r = np.random.rand()
            if r < mutation_prob:
                if pop[i][j] == 0:
                    pop[i][j] = 1
                else:
                    pop[i][j] = 0
    
    return pop

In [9]:
def genetic_algorithm(num_individuals, num_parameters, num_generations):
    pop = initialize_population(num_individuals, num_parameters)
    pop_fitness = np.array([onemax(ind) for ind in pop])
    print("#Gen 0:")
    print(pop_fitness)

    tournament_size = num_individuals // 2 

    for i in range(num_generations):
        offspring = crossover(pop)
        offspring_fitness = np.array([onemax(ind) for ind in offspring])

        pool = np.vstack([pop, offspring])
        pool_fitness = np.concatenate((pop_fitness, offspring_fitness))

        selected_indicies = tournament_selection(pool, pool_fitness)
        selection_set = pool[selected_indicies]
        selection_fitness = pool_fitness[selected_indicies]

        pop = np.copy(selection_set)
        pop_fitness = np.copy(selection_fitness)

        print(f'#Gen {i+1}:')
        print(pop_fitness)
    
    print('#Final result:')
    print(pop)
    print(pop_fitness)


### **Problem size = 8**

In [10]:
np.random.seed(19521432)

num_parameters = 8
num_individuals = 8
num_generations = 10
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[5 6 6 4 2 6 6 4]
#Gen 1:
[6 6 6 6 6 5 6 6]
#Gen 2:
[6 6 6 6 6 6 6 6]
#Gen 3:
[6 7 6 7 7 6 6 7]
#Gen 4:
[7 7 7 7 7 6 7 7]
#Gen 5:
[7 7 7 8 8 7 7 7]
#Gen 6:
[7 7 8 8 8 7 8 8]
#Gen 7:
[8 8 8 8 8 8 8 8]
#Gen 8:
[8 8 8 8 8 8 8 8]
#Gen 9:
[8 8 8 8 8 8 8 8]
#Gen 10:
[8 8 8 8 8 8 8 8]
#Final result:
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[8 8 8 8 8 8 8 8]


### **Problem size = 16**

In [11]:
np.random.seed(19521432)

num_parameters = 16
num_individuals = 16
num_generations = 10
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[11 10  8 10 11 10 11  5  7  7  7 10  6  7 11  4]
#Gen 1:
[ 8 10 10 13 10 11 11 11 10 13 10 11 11  9 11 11]
#Gen 2:
[14 13 11 12 12 13 11 12 11 13 11 14 12 12 11 13]
#Gen 3:
[13 14 13 14 14 14 13 14 14 14 13 13 14 14 13 13]
#Gen 4:
[14 15 14 14 14 13 14 15 14 14 15 14 14 14 15 14]
#Gen 5:
[14 14 15 14 14 16 15 14 15 14 15 15 16 15 14 14]
#Gen 6:
[16 15 15 15 16 16 15 16 15 16 16 15 16 16 15 14]
#Gen 7:
[16 16 16 16 16 16 16 16 16 15 16 15 16 16 16 16]
#Gen 8:
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]
#Gen 9:
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]
#Gen 10:
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]
#Final result:
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

### **Problem size = 32**

In [12]:
np.random.seed(19521432)

# Fail
num_parameters = 32
num_individuals = 32
num_generations = 20 # Always converge from gen 11 with fitness = 31 
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[21 18 21 16 14 17 13 15 14 20 16 19 14 16 15 16 20 17 11 16 13 17 15 23
 14 16 16 16 11 21 13 15]
#Gen 1:
[17 17 17 16 23 18 22 20 21 22 23 17 17 21 16 20 14 18 22 16 23 20 21 23
 16 21 17 18 20 17 17 20]
#Gen 2:
[24 21 22 25 21 23 20 23 21 20 21 22 22 23 21 22 23 17 21 20 24 23 22 17
 21 20 25 21 22 20 22 22]
#Gen 3:
[24 23 25 23 22 25 24 25 24 22 22 26 24 23 23 22 22 25 24 24 24 24 22 24
 23 23 26 22 23 25 25 22]
#Gen 4:
[26 24 26 24 24 25 25 25 25 26 25 25 24 25 25 25 26 26 24 25 25 25 24 25
 25 25 25 25 26 24 24 25]
#Gen 5:
[25 27 26 26 26 25 26 26 27 25 27 25 25 26 27 25 26 26 26 27 25 25 26 26
 27 25 27 26 27 25 26 26]
#Gen 6:
[26 28 27 27 27 26 27 27 27 26 27 27 27 27 27 27 27 27 27 27 27 26 27 27
 26 26 28 27 27 27 27 26]
#Gen 7:
[27 27 29 27 28 27 28 30 28 28 27 27 28 28 29 27 28 29 27 28 27 28 29 30
 27 27 27 28 28 27 27 28]
#Gen 8:
[28 30 28 30 29 27 28 29 28 29 29 30 29 30 30 30 29 30 30 29 30 30 29 30
 28 28 29 28 28 28 28 30]
#Gen 9:
[30 29 30 30 31 30 30 30 30 3

In [13]:
np.random.seed(19521432)

num_parameters = 32
num_individuals = 64
num_generations = 12
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[21 18 21 16 14 17 13 15 14 20 16 19 14 16 15 16 20 17 11 16 13 17 15 23
 14 16 16 16 11 21 13 15 12 15 16 18 18 14 17 17 12 12 18 14 21 16 14 21
 17 17 15 15 15 19 19 19 15 16 14 19 18 14 14 23]
#Gen 1:
[21 19 21 17 23 21 18 16 18 17 19 21 22 21 19 18 20 21 21 20 18 24 19 17
 17 18 17 20 19 20 23 19 15 18 21 21 21 19 23 19 16 20 22 19 17 24 23 20
 18 21 21 15 17 21 18 19 17 20 18 19 21 20 19 16]
#Gen 2:
[23 21 21 24 24 20 23 21 21 23 21 23 24 19 23 21 21 23 21 23 21 22 20 20
 21 21 20 21 22 23 21 22 21 23 24 21 23 21 23 21 21 24 24 19 23 22 21 21
 23 22 21 23 23 19 21 21 20 24 21 23 21 18 22 23]
#Gen 3:
[26 24 26 23 22 24 21 24 23 24 27 24 22 23 24 23 24 23 24 24 21 24 21 24
 22 23 23 23 22 22 24 24 21 22 23 23 23 26 24 24 22 24 24 23 22 23 23 24
 24 24 24 23 24 27 26 25 24 24 23 23 24 24 24 23]
#Gen 4:
[25 26 27 25 24 24 27 24 26 27 26 25 24 24 24 26 24 23 26 26 25 24 24 24
 27 24 26 26 25 24 24 25 24 27 26 25 26 25 24 24 27 24 24 27 24 25 26 25
 27 25 24 24 26 25 26 24 24 25

### **Problem size = 64**

In [14]:
np.random.seed(19521432)

num_parameters = 64
num_individuals = 64
num_generations = 18
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[39 37 31 28 34 35 30 31 37 27 30 38 30 32 32 28 27 34 32 34 24 32 37 35
 34 30 34 38 31 33 32 37 30 28 36 34 39 24 31 27 34 32 36 33 33 34 27 25
 25 34 31 29 31 31 26 32 27 30 31 39 34 35 34 37]
#Gen 1:
[32 36 37 33 37 39 39 38 37 35 31 37 38 36 35 35 34 36 38 37 35 35 39 42
 33 34 38 37 35 34 32 37 32 38 34 32 39 35 36 38 35 34 37 37 38 42 37 37
 36 36 35 38 39 35 31 37 35 37 37 35 37 36 37 39]
#Gen 2:
[38 42 35 46 42 39 38 41 37 39 37 43 37 36 37 39 40 39 39 40 39 39 40 38
 40 37 39 42 37 38 38 37 38 39 37 38 39 40 37 42 37 39 40 37 35 37 42 39
 42 40 38 39 46 39 37 43 36 36 40 38 37 41 38 41]
#Gen 3:
[42 43 43 42 42 42 42 41 42 43 40 42 46 40 38 41 40 42 41 41 43 40 47 40
 38 41 42 44 42 43 41 42 42 38 42 46 43 40 40 42 41 41 41 43 40 46 41 42
 44 40 43 42 42 40 42 43 40 47 42 42 42 40 42 42]
#Gen 4:
[45 46 42 46 46 46 43 43 45 44 44 45 45 41 47 46 42 45 43 47 44 44 42 42
 41 47 50 42 45 41 44 45 45 44 43 47 43 45 45 43 42 46 50 45 48 42 44 46
 46 47 43 43 44 44 46 45 47 45

### **Problem size = 128**

In [15]:
np.random.seed(19521432)

# Fail
num_parameters = 128
num_individuals = 64
num_generations = 26 # Converge from gen 26 with fitness = 127
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[76 59 69 61 64 68 62 60 61 66 56 72 64 72 64 69 58 70 63 58 66 69 67 52
 59 60 62 58 57 70 69 71 61 60 68 69 60 68 59 61 59 70 60 57 64 63 67 63
 68 59 55 68 55 65 63 65 58 61 55 58 63 62 66 64]
#Gen 1:
[72 67 70 68 64 69 72 68 69 71 70 72 76 64 61 70 71 68 68 70 69 72 69 74
 69 70 60 69 64 65 68 73 68 68 71 69 60 74 70 69 76 69 66 66 68 72 67 70
 64 69 74 62 67 73 69 72 72 70 72 69 64 62 68 63]
#Gen 2:
[74 70 74 69 72 71 71 73 71 69 74 76 76 83 74 76 72 74 74 76 70 75 70 70
 72 70 72 72 69 73 76 72 74 72 72 69 75 70 72 72 76 72 71 76 73 76 69 68
 71 83 73 74 72 74 73 71 67 76 75 74 76 69 71 74]
#Gen 3:
[79 83 74 76 76 76 77 79 77 74 84 79 83 72 78 79 74 75 76 76 84 80 76 76
 75 78 76 75 79 76 75 81 73 77 78 79 79 79 73 83 76 73 79 75 78 75 83 84
 80 74 72 76 76 73 76 73 84 79 77 73 81 73 77 74]
#Gen 4:
[84 80 83 85 84 76 84 79 85 81 79 78 87 78 84 84 79 79 83 79 77 80 78 89
 80 83 89 87 78 73 86 83 78 89 83 79 86 84 84 84 78 83 84 83 79 81 80 84
 79 87 79 83 80 89 79 87 78 77

In [16]:
np.random.seed(19521432)

num_parameters = 128
num_individuals = 128
num_generations = 25
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[76 59 69 61 64 68 62 60 61 66 56 72 64 72 64 69 58 70 63 58 66 69 67 52
 59 60 62 58 57 70 69 71 61 60 68 69 60 68 59 61 59 70 60 57 64 63 67 63
 68 59 55 68 55 65 63 65 58 61 55 58 63 62 66 64 60 64 48 62 59 65 69 69
 68 73 70 72 70 65 70 65 67 65 59 68 61 58 59 71 70 63 66 58 60 60 68 61
 72 73 63 71 55 74 65 72 62 56 67 68 68 59 65 60 63 67 69 72 62 59 75 61
 61 71 57 60 73 61 64 58]
#Gen 1:
[68 72 73 67 61 68 70 79 68 65 70 68 70 68 73 73 68 73 72 70 72 68 66 65
 76 73 67 70 66 72 65 75 68 62 71 72 72 70 67 69 75 63 73 73 66 73 67 71
 72 70 71 69 70 66 74 61 65 68 73 68 70 66 76 63 65 76 72 70 67 65 71 62
 67 75 75 73 73 68 71 74 72 65 73 68 71 79 73 65 64 68 68 68 73 71 68 69
 63 72 69 70 64 70 70 71 72 66 66 67 72 68 69 74 73 65 66 69 70 64 73 63
 70 69 76 65 68 70 68 73]
#Gen 2:
[72 72 73 74 74 68 70 76 73 72 74 70 74 79 77 72 75 73 76 76 74 74 71 77
 73 75 73 76 75 77 76 72 76 79 78 73 79 70 75 70 72 71 66 78 69 71 72 68
 71 75 73 73 73 73 75 75 75 73 74 73 73 76 82 72

## **Comment:**

*Specifications for parameters to converge to optimal solutions with corresponding problem size:* 


*   problem size = 8: pop size = 8, gen = 10

*   problem size = 16: pop size = 16, gen = 10

*   problem size = 32: pop size = 64, gen = 12

*   problem size = 64: pop size = 64, gen = 18

*   problem size = 128: pop size = 128, gen = 25





